import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { ScreenType, ModalType, DashPage, VideoState, VideoType, ExerciseStep, RecipeStep } from '../types';
import { calcTDEE, assignPlan } from '../utils/tdee';

interface PayInfo {
  plan: string;
  price: string;
  period: string;
}

interface AppState {
  // Navigation
  currentScreen: ScreenType;
  goTo: (screen: ScreenType) => void;

  // User
  userName: string;
  setUserName: (name: string) => void;
  startDate: string; // ISO date string YYYY-MM-DD

  // Onboarding
  obStep: number;
  obData: Record<string, string | number>;
  setObStep: (step: number) => void;
  setObData: (key: string, value: string | number) => void;
  finishOnboardingCalc: () => void; // calculates TDEE + assigns plan without navigating
  finishOnboarding: () => void;     // navigates to dashboard

  // Dashboard
  dashPage: DashPage;
  setDashPage: (page: DashPage) => void;

  // Modals
  activeModal: ModalType;
  openModal: (modal: ModalType) => void;
  closeModal: () => void;

  // Payment modal
  payInfo: PayInfo;
  openPay: (plan: string, price: string, period: string) => void;

  // Video modal
  videoState: VideoState | null;
  openVideo: (
    type: VideoType,
    title: string,
    desc: string,
    emoji: string,
    steps: ExerciseStep[] | RecipeStep[]
  ) => void;
  closeVideo: () => void;
  vidNavNext: () => void;
  vidNavPrev: () => void;
  setVideoPlaying: (playing: boolean) => void;
  setVideoStep: (step: number) => void;

  // UI state
  pillarsOpen: boolean;
  togglePillars: () => void;
  mobileSidebarOpen: boolean;
  setMobileSidebarOpen: (open: boolean) => void;
  mobileMenuOpen: boolean;
  toggleMobileMenu: () => void;

  // Dashboard habits — date-keyed history
  habits: Record<string, boolean>;
  habitsDate: string; // date the current habits state belongs to
  habitHistory: Record<string, Record<string, boolean>>; // { '2026-03-09': { agua: true, ... } }
  toggleHabit: (id: string) => void;

  // Trial expiry check
  checkTrialExpiry: () => void;

  // Weight log
  weightLog: { date: string; kg: number }[];
  addWeight: (kg: number) => void;
  removeWeight: (date: string) => void;

  // Meal check-off (tracks which meals the user actually ate)
  mealChecks: Record<string, boolean>; // { '2026-03-09-planA-1-0': true }
  toggleMealCheck: (key: string) => void;

  // Welcome video closed
  welcomeVidClosed: boolean;
  setWelcomeVidClosed: (closed: boolean) => void;

  // Meal plan assignment (admin-set, never shown as calories to the user)
  mealPlanKey: string;
  setMealPlanKey: (key: string) => void;

  // Calculated nutrition targets
  tdee: number;        // kcal/day maintenance
  planGoal: number;    // kcal/day target (tdee ± adjustment)

  // Workout log
  workoutLog: { date: string; exercise: string; sets: { reps: number; kg: number }[] }[];
  addWorkoutEntry: (exercise: string, sets: { reps: number; kg: number }[]) => void;
  removeWorkoutEntry: (date: string, exercise: string) => void;

  // Food log (manual + AI)
  foodLog: { id: string; date: string; desc: string; kcal: number; prot: number; carbs: number; fat: number; source: 'manual' | 'ai' }[];
  addFoodLog: (entry: { desc: string; kcal: number; prot: number; carbs: number; fat: number; source: 'manual' | 'ai' }) => void;
  removeFoodLog: (id: string) => void;

  // Plan / Trial
  userPlan: 'none' | 'trial' | 'basico' | 'pro' | 'elite';
  trialEndsAt: string | null;
  selectPlan: (plan: 'basico' | 'pro' | 'elite') => void;
  startTrial: (plan: 'basico' | 'pro' | 'elite') => void;

  // Growth Plan (Healthy Space Method)
  growthData: Record<number, Record<string, string>>; // step index → user answers
  growthCompleted: boolean[]; // length 10
  saveGrowthData: (step: number, data: Record<string, string>) => void;
  completeGrowthStep: (step: number) => void;

  // Nutrition plan week anchor
  shoppingDay: number | null; // day of week (0=Dom, 1=Lun ... 6=Sáb) user goes to super
  setShoppingDay: (day: number) => void;

  // Weekly nutrition plan (AI-generated)
  weeklyPlan: {
    generatedAt: string;       // ISO date
    mealPlanKey: string;
    selectedDays: number[];    // 7 DayPlan.day values (1–28)
    shoppingList: string[];
    nota: string;
    preferences: string;
  } | null;
  saveWeeklyPlan: (plan: NonNullable<AppState['weeklyPlan']>) => void;
  clearWeeklyPlan: () => void;

  // Daily workout (generated by AI coach)
  dailyWorkout: { date: string; plan: Record<string, unknown> } | null;
  saveDailyWorkout: (plan: Record<string, unknown>) => void;
  dailyWorkoutChecked: number[];
  toggleDailyWorkoutCheck: (i: number) => void;

  // Weekly review
  lastWeeklyReview: string | null; // ISO date of last Sunday review
  markWeeklyReviewDone: () => void;

  // Weekly plan regen limit (max 2/week)
  planRegenCount: { weekStart: string; count: number } | null;
  incrementPlanRegen: () => void;

  // Daily check-in + streak
  dailyCheckIn: { date: string; feeling: string; sleep: string } | null;
  saveDailyCheckIn: (data: { feeling: string; sleep: string }) => void;
  streakCount: number;
  lastActiveDate: string | null;

  // Daily AI briefing (cached per day)
  dailyBriefing: { date: string; message: string } | null;
  setDailyBriefing: (b: { date: string; message: string }) => void;

  // Streak milestones already celebrated
  lastStreakMilestone: number;
  setLastStreakMilestone: (n: number) => void;

  // Daily energy check-in (Hoy tab)
  dailyCheckin: 'cansado' | 'regular' | 'energia' | null;
  dailyCheckinDate: string;
  setDailyCheckin: (val: 'cansado' | 'regular' | 'energia') => void;

  // Daily HSM micro-responses
  dailyHSMResponses: { date: string; dimension: string; question: string; response: string }[];
  addHSMResponse: (entry: { dimension: string; question: string; response: string }) => void;

  // Coach chat history (resets daily)
  coachChatHistory: { role: 'user' | 'assistant'; content: string; timestamp: string }[];
  coachChatDate: string;
  addCoachMessage: (role: 'user' | 'assistant', content: string) => void;
  clearCoachChat: () => void;

  // Active HSM dimension + unlock tracking
  activeHSMDimension: number;
  setActiveHSMDimension: (n: number) => void;
  hsmUnlockDays: number[];

  // Cumulative HSM profile (updated weekly by AI)
  hsmProfile: { text: string; updatedAt: string } | null;
  setHSMProfile: (text: string) => void;

  // Night check-in
  nightCheckIn: {
    date: string;
    energia: string;
    cumplimiento: string;
    valores: string;
    reflexion: string;
    intencionManana: string;
    completed: boolean;
  } | null;
  saveNightCheckIn: (data: {
    energia: string; cumplimiento: string; valores: string;
    reflexion: string; intencionManana: string;
  }) => void;

  // Logout
  logout: () => void;
}

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
  // Navigation
  currentScreen: 'landing',
  goTo: (screen) => set({ currentScreen: screen }),

  // User
  userName: '',
  setUserName: (name) => set({ userName: name }),
  startDate: '',

  // Onboarding
  obStep: 1,
  obData: {},
  setObStep: (step) => set({ obStep: step }),
  setObData: (key, value) =>
    set((state) => ({ obData: { ...state.obData, [key]: value } })),
  // Calculate TDEE + assign plan WITHOUT navigating (called during processing step)
  finishOnboardingCalc: () => {
    const { obData, setUserName } = get();
    if (obData.name) setUserName(String(obData.name));

    const sexo      = String(obData.sex      || 'Hombre');
    const pesoKg    = Number(obData.peso     || 70);
    const estatura  = Number(obData.estatura || 170);
    const edad      = Number(obData.edad     || 28);
    const activity  = String(obData.activity || 'Moderada');
    const goal      = String(obData.goal     || '');

    const tdee       = calcTDEE(sexo, pesoKg, estatura, edad, activity);
    const planKey    = assignPlan(tdee, goal);

    let planGoal = tdee;
    if      (goal === 'Bajar grasa corporal' || goal === 'Bajar grasa' || goal === 'Bajar de peso') planGoal = tdee - 500;
    else if (goal === 'Subir masa muscular' || goal === 'Ganar músculo') planGoal = tdee + 300;
    else if (goal === 'Recomposición' || goal === 'Recomponer') planGoal = tdee - 200;
    // Bienestar integral → maintenance (tdee as-is)

    const trialEndsAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();

    set({
      mealPlanKey: planKey,
      tdee,
      planGoal,
      startDate: new Date().toISOString().split('T')[0],
      userPlan: 'pro',
      trialEndsAt,
    });
  },

  // Navigate to dashboard (called when user taps "Entrar a mi espacio")
  finishOnboarding: () => {
    set({
      currentScreen: 'dashboard',
      obStep: 1,
      activeModal: null,
    });
  },

  // Dashboard
  dashPage: 'hoy',
  setDashPage: (page) => set({ dashPage: page }),

  // Modals
  activeModal: null,
  openModal: (modal) => set({ activeModal: modal }),
  closeModal: () => set({ activeModal: null }),

  // Payment modal
  payInfo: { plan: '', price: '', period: '' },
  openPay: (plan, price, period) =>
    set({ payInfo: { plan, price, period }, activeModal: 'pay' }),

  // Video modal
  videoState: null,
  openVideo: (type, title, desc, emoji, steps) =>
    set({
      videoState: { type, title, desc, emoji, steps, currentStep: 0, playing: false },
      activeModal: 'video',
    }),
  closeVideo: () => set({ activeModal: null, videoState: null }),
  vidNavNext: () =>
    set((state) => {
      if (!state.videoState) return {};
      const max = state.videoState.steps.length - 1;
      const next = Math.min(state.videoState.currentStep + 1, max);
      return { videoState: { ...state.videoState, currentStep: next } };
    }),
  vidNavPrev: () =>
    set((state) => {
      if (!state.videoState) return {};
      const prev = Math.max(state.videoState.currentStep - 1, 0);
      return { videoState: { ...state.videoState, currentStep: prev } };
    }),
  setVideoPlaying: (playing) =>
    set((state) =>
      state.videoState ? { videoState: { ...state.videoState, playing } } : {}
    ),
  setVideoStep: (step) =>
    set((state) =>
      state.videoState ? { videoState: { ...state.videoState, currentStep: step } } : {}
    ),

  // UI state
  pillarsOpen: false,
  togglePillars: () => set((state) => ({ pillarsOpen: !state.pillarsOpen })),
  mobileSidebarOpen: false,
  setMobileSidebarOpen: (open) => set({ mobileSidebarOpen: open }),
  mobileMenuOpen: false,
  toggleMobileMenu: () =>
    set((state) => ({ mobileMenuOpen: !state.mobileMenuOpen })),

  // Habits — persist today's state into history on toggle
  habits: {
    agua: false,
    frutas: false,
    ejercicio: false,
    sueno: false,
  },
  habitsDate: '',
  habitHistory: {},
  toggleHabit: (id) =>
    set((state) => {
      const today = new Date().toISOString().split('T')[0];
      // Reset habits if it's a new day
      const baseHabits = state.habitsDate === today
        ? state.habits
        : { agua: false, frutas: false, ejercicio: false, sueno: false };
      const updated = { ...baseHabits, [id]: !baseHabits[id] };
      return {
        habits: updated,
        habitsDate: today,
        habitHistory: { ...state.habitHistory, [today]: updated },
      };
    }),

  // Weight log
  weightLog: [],
  addWeight: (kg) =>
    set((state) => {
      const today = new Date().toISOString().split('T')[0];
      const filtered = state.weightLog.filter(e => e.date !== today);
      return { weightLog: [...filtered, { date: today, kg }].sort((a, b) => a.date.localeCompare(b.date)) };
    }),
  removeWeight: (date) =>
    set((state) => ({ weightLog: state.weightLog.filter(e => e.date !== date) })),

  // Meal check-off
  mealChecks: {},
  toggleMealCheck: (key) =>
    set((state) => ({ mealChecks: { ...state.mealChecks, [key]: !state.mealChecks[key] } })),

  // Welcome video
  welcomeVidClosed: false,
  setWelcomeVidClosed: (closed) => set({ welcomeVidClosed: closed }),

  // Meal plan assignment
  mealPlanKey: 'planA',
  setMealPlanKey: (key) => set({ mealPlanKey: key }),

  // Nutrition targets (calculated after onboarding)
  tdee: 0,
  planGoal: 0,

  // Workout log
  workoutLog: [],
  addWorkoutEntry: (exercise, sets) =>
    set((state) => {
      const today = new Date().toISOString().split('T')[0];
      return { workoutLog: [...state.workoutLog, { date: today, exercise, sets }] };
    }),
  removeWorkoutEntry: (date, exercise) =>
    set((state) => ({
      workoutLog: state.workoutLog.filter(e => !(e.date === date && e.exercise === exercise)),
    })),

  // Food log
  foodLog: [],
  addFoodLog: (entry) =>
    set((state) => {
      const today = new Date().toISOString().split('T')[0];
      const id = `${today}-${Date.now()}`;
      return { foodLog: [...state.foodLog, { id, date: today, ...entry }] };
    }),
  removeFoodLog: (id) =>
    set((state) => ({ foodLog: state.foodLog.filter(e => e.id !== id) })),

  // Trial expiry
  checkTrialExpiry: () => {
    const { userPlan, trialEndsAt } = get();
    if (userPlan === 'trial' && trialEndsAt && new Date(trialEndsAt).getTime() < Date.now()) {
      set({ userPlan: 'none', trialEndsAt: null });
    }
  },

  // Nutrition week anchor
  shoppingDay: null,
  setShoppingDay: (day) => set({ shoppingDay: day }),

  // Weekly nutrition plan
  weeklyPlan: null,
  saveWeeklyPlan: (plan) => set({ weeklyPlan: plan }),
  clearWeeklyPlan: () => set({ weeklyPlan: null }),

  // Weekly review
  lastWeeklyReview: null,
  markWeeklyReviewDone: () => set({ lastWeeklyReview: new Date().toISOString().split('T')[0] }),

  // Weekly plan regen limit
  planRegenCount: null,
  incrementPlanRegen: () => {
    const weekStart = (() => {
      const d = new Date();
      d.setDate(d.getDate() - d.getDay()); // Sunday anchor
      return d.toISOString().split('T')[0];
    })();
    const current = get().planRegenCount;
    const sameWeek = current?.weekStart === weekStart;
    set({ planRegenCount: { weekStart, count: sameWeek ? (current!.count + 1) : 1 } });
  },

  // Daily workout
  dailyWorkout: null,
  saveDailyWorkout: (plan) =>
    set({ dailyWorkout: { date: new Date().toISOString().split('T')[0], plan }, dailyWorkoutChecked: [] }),
  dailyWorkoutChecked: [],
  toggleDailyWorkoutCheck: (i) =>
    set((state) => {
      const next = state.dailyWorkoutChecked.includes(i)
        ? state.dailyWorkoutChecked.filter(x => x !== i)
        : [...state.dailyWorkoutChecked, i];
      return { dailyWorkoutChecked: next };
    }),

  // Daily AI briefing
  dailyBriefing: null,
  setDailyBriefing: (b) => set({ dailyBriefing: b }),

  // Streak milestones
  lastStreakMilestone: 0,
  setLastStreakMilestone: (n) => set({ lastStreakMilestone: n }),

  // Daily check-in + streak
  dailyCheckIn: null,
  streakCount: 0,
  lastActiveDate: null,
  saveDailyCheckIn: (data) => {
    const today = new Date().toISOString().split('T')[0];
    const { lastActiveDate, streakCount } = get();
    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
    const newStreak = lastActiveDate === today
      ? streakCount
      : lastActiveDate === yesterday
        ? streakCount + 1
        : 1;
    set({ dailyCheckIn: { date: today, ...data }, lastActiveDate: today, streakCount: newStreak });
  },

  // Growth Plan (Healthy Space Method)
  growthData: {},
  growthCompleted: Array(10).fill(false),
  saveGrowthData: (step, data) =>
    set((state) => ({ growthData: { ...state.growthData, [step]: { ...(state.growthData[step] ?? {}), ...data } } })),
  completeGrowthStep: (step) =>
    set((state) => {
      const next = [...state.growthCompleted];
      next[step] = true;
      return { growthCompleted: next };
    }),

  // Plan / Trial
  userPlan: 'none',
  trialEndsAt: null,
  startTrial: (plan) => {
    const endsAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
    set({ userPlan: plan, trialEndsAt: endsAt });
  },
  selectPlan: (plan) => set({ userPlan: plan, trialEndsAt: null }),

  // Daily energy check-in (Hoy tab) — also updates streak
  dailyCheckin: null,
  dailyCheckinDate: '',
  setDailyCheckin: (val) => {
    const today = new Date().toISOString().split('T')[0];
    const { lastActiveDate, streakCount, hsmUnlockDays, startDate } = get();
    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
    const newStreak = lastActiveDate === today
      ? streakCount
      : lastActiveDate === yesterday
        ? streakCount + 1
        : 1;
    // Track active day for HSM unlock
    const dayIndex = startDate ? Math.floor((Date.now() - new Date(startDate).getTime()) / 86400000) : 0;
    const updatedUnlockDays = hsmUnlockDays.includes(dayIndex) ? hsmUnlockDays : [...hsmUnlockDays, dayIndex];
    set({
      dailyCheckin: val,
      dailyCheckinDate: today,
      lastActiveDate: today,
      streakCount: newStreak,
      hsmUnlockDays: updatedUnlockDays,
    });
  },

  // Daily HSM micro-responses
  dailyHSMResponses: [],
  addHSMResponse: (entry) => {
    const today = new Date().toISOString().split('T')[0];
    set((state) => ({
      dailyHSMResponses: [...state.dailyHSMResponses, { date: today, ...entry }],
    }));
  },

  // Coach chat history
  coachChatHistory: [],
  coachChatDate: '',
  addCoachMessage: (role, content) => {
    const today = new Date().toISOString().split('T')[0];
    set((state) => {
      const history = state.coachChatDate === today ? state.coachChatHistory : [];
      return {
        coachChatHistory: [...history, { role, content, timestamp: new Date().toISOString() }],
        coachChatDate: today,
      };
    });
  },
  clearCoachChat: () => set({ coachChatHistory: [], coachChatDate: '' }),

  // Active HSM dimension + unlock tracking
  activeHSMDimension: 0,
  setActiveHSMDimension: (n) => set({ activeHSMDimension: n }),
  hsmUnlockDays: [],

  // Cumulative HSM profile
  hsmProfile: null,
  setHSMProfile: (text) => set({ hsmProfile: { text, updatedAt: new Date().toISOString().split('T')[0] } }),

  // Night check-in — also maintains streak for the day
  nightCheckIn: null,
  saveNightCheckIn: (data) => {
    const today = new Date().toISOString().split('T')[0];
    const { lastActiveDate, streakCount } = get();
    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
    const newStreak = lastActiveDate === today
      ? streakCount
      : lastActiveDate === yesterday
        ? streakCount + 1
        : 1;
    set({
      nightCheckIn: { date: today, ...data, completed: true },
      lastActiveDate: today,
      streakCount: newStreak,
    });
  },

  // Logout — signs out of Supabase and clears all local state
  logout: () => {
    import('../lib/supabase').then(({ supabase }) => supabase.auth.signOut());
    localStorage.removeItem('hsc-life-system-v2');
    set({
      currentScreen: 'landing',
      userName: '',
      obStep: 1,
      obData: {},
      startDate: '',
      dashPage: 'hoy',
      activeModal: null,
      videoState: null,
      pillarsOpen: false,
      mobileSidebarOpen: false,
      mobileMenuOpen: false,
      habits: { agua: false, frutas: false, ejercicio: false, sueno: false },
      habitHistory: {},
      weightLog: [],
      mealChecks: {},
      welcomeVidClosed: false,
      mealPlanKey: 'planA',
      tdee: 0,
      planGoal: 0,
      workoutLog: [],
      foodLog: [],
      userPlan: 'none',
      trialEndsAt: null,
      growthData: {},
      growthCompleted: Array(10).fill(false),
      dailyWorkout: null,
      dailyWorkoutChecked: [],
      shoppingDay: null,
      weeklyPlan: null,
      dailyCheckIn: null,
      streakCount: 0,
      lastActiveDate: null,
      planRegenCount: null,
      lastWeeklyReview: null,
      dailyBriefing: null,
      lastStreakMilestone: 0,
      dailyCheckin: null,
      dailyCheckinDate: '',
      dailyHSMResponses: [],
      coachChatHistory: [],
      coachChatDate: '',
      activeHSMDimension: 0,
      hsmUnlockDays: [],
      hsmProfile: null,
      nightCheckIn: null,
    });
  },
}),
{
  name: 'hsc-store',
  partialize: (state) => ({
    userName: state.userName,
    obData: state.obData,
    startDate: state.startDate,
    habits: state.habits,
    habitsDate: state.habitsDate,
    habitHistory: state.habitHistory,
    weightLog: state.weightLog,
    mealChecks: state.mealChecks,
    welcomeVidClosed: state.welcomeVidClosed,
    mealPlanKey: state.mealPlanKey,
    tdee: state.tdee,
    planGoal: state.planGoal,
    workoutLog: state.workoutLog,
    foodLog: state.foodLog,
    currentScreen: state.currentScreen === 'landing' ? 'landing' : state.currentScreen,
    userPlan: state.userPlan,
    trialEndsAt: state.trialEndsAt,
    growthData: state.growthData,
    growthCompleted: state.growthCompleted,
    shoppingDay: state.shoppingDay,
    weeklyPlan: state.weeklyPlan,
    dailyWorkout: state.dailyWorkout,
    dailyWorkoutChecked: state.dailyWorkoutChecked,
    dailyCheckIn: state.dailyCheckIn,
    streakCount: state.streakCount,
    lastActiveDate: state.lastActiveDate,
    planRegenCount: state.planRegenCount,
    lastWeeklyReview: state.lastWeeklyReview,
    dailyBriefing: state.dailyBriefing,
    lastStreakMilestone: state.lastStreakMilestone,
    dailyCheckin: state.dailyCheckin,
    dailyCheckinDate: state.dailyCheckinDate,
    dailyHSMResponses: state.dailyHSMResponses,
    coachChatHistory: state.coachChatHistory,
    coachChatDate: state.coachChatDate,
    activeHSMDimension: state.activeHSMDimension,
    hsmUnlockDays: state.hsmUnlockDays,
    hsmProfile: state.hsmProfile,
    nightCheckIn: state.nightCheckIn,
  }),
}
  )
);
