-- ════════════════════════════════════════════════════════════════
-- SEED: banco de platillos (BORRADOR de los 28 días, emparejado con criterio LLM)
-- 82 platillos con nombre (Desayuno/Comida/Cena), 251 ingredientes con gramos.
-- Ingredientes con medida casera sin conversión = ing_por_definir (se muestran como '+N por definir').
-- Contenido PROVISIONAL: se reemplaza cuando Magaly entregue su captura definitiva.
-- ════════════════════════════════════════════════════════════════

alter table public.platillos add column if not exists ing_por_definir int not null default 0;

delete from public.platillos where es_banco = true;

with ins as (
  insert into public.platillos (nombre, es_banco, tiempo, ing_por_definir) values
    ('Chilaquiles Ligeros', true, 'desayuno', 1),
    ('Alambre de Pollo', true, 'comida', 1),
    ('Ceviche de Panela', true, 'cena', 2),
    ('Omelette', true, 'desayuno', 2),
    ('Caldo de Pollo', true, 'comida', 1),
    ('Molletes', true, 'cena', 0),
    ('Machaca con Nopales', true, 'desayuno', 5),
    ('Tacos de Pescado', true, 'comida', 2),
    ('Enfrijoladas', true, 'cena', 1),
    ('Huevos Rancheros', true, 'desayuno', 1),
    ('Tinga de Pollo', true, 'comida', 4),
    ('Quesadillas con Champiñones', true, 'cena', 1),
    ('Molletes con Huevo', true, 'desayuno', 1),
    ('Asado de Res', true, 'comida', 1),
    ('Ceviche de Atún', true, 'cena', 4),
    ('Bowl de Amaranto', true, 'desayuno', 4),
    ('Carne Molida con Verduras y Arroz', true, 'comida', 3),
    ('Tacos de Camarón', true, 'cena', 2),
    ('Calabacitas', true, 'desayuno', 2),
    ('Bistec de Res', true, 'comida', 1),
    ('Ensalada Cremosa de Atún', true, 'cena', 4),
    ('Yogurt Coco-Mango', true, 'desayuno', 3),
    ('Pollo Teriyaki', true, 'comida', 1),
    ('Fideos con Verdura', true, 'cena', 4),
    ('Bowl', true, 'desayuno', 1),
    ('Poké Bowl', true, 'comida', 5),
    ('Sopa Miso', true, 'cena', 4),
    ('Avena con Manzana', true, 'desayuno', 3),
    ('Ramen Ligero', true, 'comida', 1),
    ('Dumpling Rolls', true, 'cena', 4),
    ('Pancakes de Camote', true, 'desayuno', 2),
    ('Salmón al Limón', true, 'comida', 4),
    ('Crema de Calabacín', true, 'cena', 1),
    ('Rice Pudding Japonés', true, 'desayuno', 1),
    ('Bowl de Camote', true, 'comida', 4),
    ('Croquetas de Papa', true, 'cena', 5),
    ('Smoothie de Plátano', true, 'desayuno', 5),
    ('Pollo con Verduras', true, 'comida', 4),
    ('Brochetas Yakitori', true, 'cena', 2),
    ('Toast de Huevo', true, 'desayuno', 7),
    ('Bowl de Camarón', true, 'comida', 3),
    ('Gohan de Salmón y Espinaca', true, 'cena', 6),
    ('Ricotta Toast Durazno', true, 'desayuno', 3),
    ('Ensalada Griega', true, 'comida', 6),
    ('Minestrone Ligera', true, 'cena', 0),
    ('Huevos Mediterráneos', true, 'desayuno', 2),
    ('Filete de Pescado', true, 'comida', 4),
    ('Puré de Camote', true, 'cena', 0),
    ('Toast', true, 'desayuno', 1),
    ('Bowl de Atún', true, 'comida', 3),
    ('Pimientos Rellenos', true, 'cena', 3),
    ('Bowl de Durazno', true, 'desayuno', 2),
    ('Lasaña de Calabacín', true, 'comida', 2),
    ('Wrap de Pollo', true, 'cena', 2),
    ('Smoothie de Frutos Rojos', true, 'desayuno', 4),
    ('Bowl de Garbanzo', true, 'comida', 1),
    ('Bowl Balanceado con Pollo', true, 'cena', 1),
    ('Toast de Pera y Maní', true, 'desayuno', 4),
    ('Pasta con Verduras', true, 'comida', 1),
    ('Pan Pizza', true, 'cena', 1),
    ('Ricotta Toast', true, 'desayuno', 3),
    ('Pollo al Romero', true, 'comida', 1),
    ('Ensalada Caprese', true, 'cena', 2),
    ('Lemon Overnight Oats', true, 'desayuno', 4),
    ('Hamburguesa Ligera', true, 'comida', 1),
    ('Carne Asada con Ensalada de Aguacate', true, 'cena', 6),
    ('Bagel de Salmón', true, 'desayuno', 2),
    ('Chicken Bowl', true, 'comida', 3),
    ('Papa Rellena al Horno', true, 'cena', 1),
    ('Ensalada Cobb', true, 'comida', 5),
    ('Chicken Honey Mustard Bowl', true, 'cena', 7),
    ('Desayuno Americano', true, 'desayuno', 3),
    ('Salmón con Quinoa Bowl', true, 'comida', 3),
    ('Chicken Tenders Fit', true, 'cena', 7),
    ('Wrap', true, 'desayuno', 2),
    ('Chicken Caesar Bowl', true, 'comida', 4),
    ('Sandwich de Atún', true, 'cena', 3),
    ('Shrimp Bowl', true, 'comida', 4),
    ('Sandwich de Guacamole', true, 'cena', 4),
    ('Apple Crumble Avena Horneada', true, 'desayuno', 3),
    ('Tacos Tex Mex', true, 'comida', 1),
    ('Mac & Cheese Ligero', true, 'cena', 4)
  returning id, nombre
)
insert into public.platillo_ingredientes (platillo_id, food_id, gramos, orden)
select i.id, x.food_id, x.gramos, x.orden
from ins i
join (values
  ('Chilaquiles Ligeros', 'huevo-entero-fresco', 88, 0),
  ('Chilaquiles Ligeros', 'queso-panela', 60, 1),
  ('Chilaquiles Ligeros', 'aguacate-hass', 63, 2),
  ('Alambre de Pollo', 'pechuga-de-pollo-sin-piel', 200, 0),
  ('Alambre de Pollo', 'queso-oaxaca', 30, 1),
  ('Alambre de Pollo', 'arroz-cocido', 376, 2),
  ('Ceviche de Panela', 'queso-panela', 150, 0),
  ('Ceviche de Panela', 'aguacate-hass', 31, 1),
  ('Omelette', 'huevo-entero-fresco', 176, 0),
  ('Omelette', 'pechuga-de-pavo', 85, 1),
  ('Omelette', 'pan-integral', 100, 2),
  ('Omelette', 'moras', 144, 3),
  ('Caldo de Pollo', 'pechuga-de-pollo-sin-piel-cocida', 200, 0),
  ('Caldo de Pollo', 'arroz-cocido', 564, 1),
  ('Molletes', 'pan-integral', 75, 0),
  ('Molletes', 'frijol-molido', 74, 1),
  ('Molletes', 'queso-panela', 100, 2),
  ('Machaca con Nopales', 'machaca', 40, 0),
  ('Machaca con Nopales', 'tortilla-de-maiz', 120, 1),
  ('Machaca con Nopales', 'aguacate-hass', 47, 2),
  ('Machaca con Nopales', 'naranja', 76, 3),
  ('Tacos de Pescado', 'filete-de-pescado-blanco-del-nilo', 160, 0),
  ('Tacos de Pescado', 'tortilla-de-maiz', 120, 1),
  ('Enfrijoladas', 'tortilla-de-maiz', 120, 0),
  ('Enfrijoladas', 'frijol-promedio-cocido', 57, 1),
  ('Enfrijoladas', 'queso-panela', 120, 2),
  ('Huevos Rancheros', 'huevo-entero-fresco', 264, 0),
  ('Huevos Rancheros', 'frijol-promedio-cocido', 115, 1),
  ('Huevos Rancheros', 'tortilla-de-maiz', 30, 2),
  ('Huevos Rancheros', 'aguacate-hass', 47, 3),
  ('Tinga de Pollo', 'pechuga-sin-piel-deshebrada', 230, 0),
  ('Tinga de Pollo', 'arroz-cocido', 564, 1),
  ('Quesadillas con Champiñones', 'tortilla-de-maiz', 60, 0),
  ('Quesadillas con Champiñones', 'queso-panela', 150, 1),
  ('Quesadillas con Champiñones', 'caldo', 240, 2),
  ('Molletes con Huevo', 'pan-integral', 100, 0),
  ('Molletes con Huevo', 'frijol-molido', 147, 1),
  ('Molletes con Huevo', 'huevo-entero-fresco', 88, 2),
  ('Molletes con Huevo', 'queso-panela', 60, 3),
  ('Asado de Res', 'carne-de-res-promedio', 200, 0),
  ('Asado de Res', 'papa-cocida', 136, 1),
  ('Asado de Res', 'queso-panela', 30, 2),
  ('Asado de Res', 'aguacate-hass', 31, 3),
  ('Ceviche de Atún', 'atun-en-agua-drenado', 200, 0),
  ('Ceviche de Atún', 'aguacate-hass', 31, 1),
  ('Ceviche de Atún', 'pan-integral', 100, 2),
  ('Bowl de Amaranto', 'yoghurt-natural', 227, 0),
  ('Bowl de Amaranto', 'fruta-picada', 35, 1),
  ('Bowl de Amaranto', 'nueces-mixtas', 10, 2),
  ('Carne Molida con Verduras y Arroz', 'molida-de-res', 230, 0),
  ('Carne Molida con Verduras y Arroz', 'arroz-cocido', 564, 1),
  ('Carne Molida con Verduras y Arroz', 'queso-panela', 60, 2),
  ('Tacos de Camarón', 'camaron-crudo-mediano', 180, 0),
  ('Tacos de Camarón', 'tortilla-de-maiz', 120, 1),
  ('Calabacitas', 'huevo-entero-fresco', 132, 0),
  ('Calabacitas', 'pan-integral', 100, 1),
  ('Bistec de Res', 'bistec-de-res', 200, 0),
  ('Bistec de Res', 'arroz-cocido', 376, 1),
  ('Ensalada Cremosa de Atún', 'atun-en-agua-drenado', 200, 0),
  ('Ensalada Cremosa de Atún', 'papa-cocida', 272, 1),
  ('Ensalada Cremosa de Atún', 'pan-integral', 100, 2),
  ('Yogurt Coco-Mango', 'yoghurt-natural', 227, 0),
  ('Yogurt Coco-Mango', 'mango-picado', 165, 1),
  ('Yogurt Coco-Mango', 'platano', 54, 2),
  ('Pollo Teriyaki', 'pechuga-de-pollo-sin-piel', 200, 0),
  ('Pollo Teriyaki', 'arroz-cocido', 376, 1),
  ('Pollo Teriyaki', 'edamame', 96, 2),
  ('Fideos con Verdura', 'fideo-cocido', 80, 0),
  ('Fideos con Verdura', 'tofu-firme', 180, 1),
  ('Bowl', 'huevo-cocido', 176, 0),
  ('Bowl', 'queso-fresco-de-cabra', 30, 1),
  ('Bowl', 'aguacate-hass', 31, 2),
  ('Bowl', 'blueberries', 48, 3),
  ('Bowl', 'pan-integral', 100, 4),
  ('Poké Bowl', 'arroz-cocido', 376, 0),
  ('Poké Bowl', 'pechuga-de-pollo-sin-piel', 200, 1),
  ('Poké Bowl', 'queso-crema', 30, 2),
  ('Poké Bowl', 'aguacate-hass', 31, 3),
  ('Sopa Miso', 'tofu-firme', 200, 0),
  ('Sopa Miso', 'fideo-cocido', 80, 1),
  ('Avena con Manzana', 'avena-en-hojuelas', 40, 0),
  ('Avena con Manzana', 'leche', 480, 1),
  ('Avena con Manzana', 'manzana', 106, 2),
  ('Avena con Manzana', 'huevo-revuelto', 5, 3),
  ('Ramen Ligero', 'fideo-cocido', 120, 0),
  ('Ramen Ligero', 'pechuga-de-pollo-sin-piel', 200, 1),
  ('Ramen Ligero', 'huevo-entero-cocido', 88, 2),
  ('Dumpling Rolls', 'molida-de-res', 200, 0),
  ('Dumpling Rolls', 'lechuga', 180, 1),
  ('Pancakes de Camote', 'pure-de-camote', 480, 0),
  ('Pancakes de Camote', 'huevo-entero-fresco', 44, 1),
  ('Pancakes de Camote', 'yoghurt-natural', 57, 2),
  ('Pancakes de Camote', 'miel', 7, 3),
  ('Salmón al Limón', 'salmon', 180, 0),
  ('Salmón al Limón', 'papa-cocida', 136, 1),
  ('Salmón al Limón', 'arroz-cocido', 188, 2),
  ('Crema de Calabacín', 'cebolla-blanca-rebanada', 29, 0),
  ('Crema de Calabacín', 'leche-semidescremada', 116, 1),
  ('Crema de Calabacín', 'caldo', 240, 2),
  ('Crema de Calabacín', 'queso-mozzarella-rallado', 120, 3),
  ('Crema de Calabacín', 'pan-integral', 75, 4),
  ('Rice Pudding Japonés', 'leche-descremada', 245, 0),
  ('Rice Pudding Japonés', 'arroz-cocido', 376, 1),
  ('Rice Pudding Japonés', 'huevo-entero-fresco', 132, 2),
  ('Bowl de Camote', 'pollo-sin-piel-cocido', 180, 0),
  ('Bowl de Camote', 'aguacate-hass', 31, 1),
  ('Croquetas de Papa', 'pechuga-sin-piel-desmenuzada', 200, 0),
  ('Smoothie de Plátano', 'platano', 108, 0),
  ('Smoothie de Plátano', 'espinaca-cruda', 60, 1),
  ('Smoothie de Plátano', 'leche', 240, 2),
  ('Smoothie de Plátano', 'huevo-entero-fresco', 88, 3),
  ('Smoothie de Plátano', 'yoghurt-natural', 114, 4),
  ('Pollo con Verduras', 'pechuga-de-pollo-sin-piel', 180, 0),
  ('Pollo con Verduras', 'papa-al-horno-con-cascara', 312, 1),
  ('Brochetas Yakitori', 'carne-de-res-promedio', 180, 0),
  ('Brochetas Yakitori', 'arroz-cocido', 376, 1),
  ('Toast de Huevo', 'pan-integral', 75, 0),
  ('Toast de Huevo', 'aguacate-hass', 23, 1),
  ('Toast de Huevo', 'huevo-entero-fresco', 132, 2),
  ('Toast de Huevo', 'yoghurt-natural', 170, 3),
  ('Toast de Huevo', 'moras', 72, 4),
  ('Bowl de Camarón', 'camaron-crudo-mediano', 200, 0),
  ('Bowl de Camarón', 'arroz-cocido', 376, 1),
  ('Gohan de Salmón y Espinaca', 'salmon', 200, 0),
  ('Gohan de Salmón y Espinaca', 'arroz-cocido', 376, 1),
  ('Gohan de Salmón y Espinaca', 'aguacate-hass', 31, 2),
  ('Ricotta Toast Durazno', 'pan-integral', 100, 0),
  ('Ricotta Toast Durazno', 'durazno-amarillo', 76, 1),
  ('Ensalada Griega', 'pechuga-de-pollo-sin-piel-a-la-plancha', 180, 0),
  ('Ensalada Griega', 'garbanzo-cocido', 164, 1),
  ('Ensalada Griega', 'arroz-cocido', 376, 2),
  ('Minestrone Ligera', 'pasta-cocida', 240, 0),
  ('Minestrone Ligera', 'pechuga-de-pollo-sin-piel', 90, 1),
  ('Minestrone Ligera', 'frijol-promedio-cocido', 172, 2),
  ('Huevos Mediterráneos', 'huevo-entero-fresco', 220, 0),
  ('Huevos Mediterráneos', 'pan-integral', 75, 1),
  ('Filete de Pescado', 'pescado-blanco', 200, 0),
  ('Filete de Pescado', 'arroz-cocido', 564, 1),
  ('Puré de Camote', 'camote-cocido', 209, 0),
  ('Puré de Camote', 'pechuga-de-pollo-sin-piel', 200, 1),
  ('Puré de Camote', 'brocoli-cocido', 184, 2),
  ('Toast', 'pan-integral', 50, 0),
  ('Toast', 'aguacate-hass', 31, 1),
  ('Toast', 'huevo-estrellado', 138, 2),
  ('Toast', 'kiwi', 76, 3),
  ('Bowl de Atún', 'atun-en-agua-drenado', 200, 0),
  ('Bowl de Atún', 'arroz-cocido', 564, 1),
  ('Bowl de Atún', 'garbanzo-cocido', 82, 2),
  ('Pimientos Rellenos', 'maciza-de-res', 200, 0),
  ('Pimientos Rellenos', 'papa-cocida', 136, 1),
  ('Pimientos Rellenos', 'arroz-cocido', 94, 2),
  ('Pimientos Rellenos', 'aguacate-hass', 47, 3),
  ('Bowl de Durazno', 'yoghurt-natural', 340, 0),
  ('Bowl de Durazno', 'avena-en-hojuelas', 40, 1),
  ('Bowl de Durazno', 'pan-integral', 75, 2),
  ('Lasaña de Calabacín', 'molida-de-res', 180, 0),
  ('Lasaña de Calabacín', 'pure-de-jitomate', 55, 1),
  ('Lasaña de Calabacín', 'queso-ricotta', 30, 2),
  ('Wrap de Pollo', 'tortilla-de-harina-integral', 56, 0),
  ('Wrap de Pollo', 'pechuga-de-pollo-sin-piel', 150, 1),
  ('Wrap de Pollo', 'papa-al-horno-con-cascara', 312, 2),
  ('Smoothie de Frutos Rojos', 'yoghurt-natural', 114, 0),
  ('Smoothie de Frutos Rojos', 'leche', 240, 1),
  ('Smoothie de Frutos Rojos', 'moras', 72, 2),
  ('Smoothie de Frutos Rojos', 'pan-tostado', 60, 3),
  ('Bowl de Garbanzo', 'garbanzo-cocido', 164, 0),
  ('Bowl de Garbanzo', 'pechuga-de-pollo-sin-piel', 180, 1),
  ('Bowl Balanceado con Pollo', 'pan-integral', 100, 0),
  ('Bowl Balanceado con Pollo', 'requeson-promedio', 30, 1),
  ('Bowl Balanceado con Pollo', 'huevo-entero-fresco', 44, 2),
  ('Bowl Balanceado con Pollo', 'pechuga-de-pollo-sin-piel', 60, 3),
  ('Bowl Balanceado con Pollo', 'manzana', 106, 4),
  ('Bowl Balanceado con Pollo', 'aguacate-hass', 31, 5),
  ('Toast de Pera y Maní', 'pan-integral', 75, 0),
  ('Toast de Pera y Maní', 'pera', 162, 1),
  ('Toast de Pera y Maní', 'huevo-entero-fresco', 132, 2),
  ('Pasta con Verduras', 'pasta-cocida', 240, 0),
  ('Pasta con Verduras', 'pechuga-de-pollo-sin-piel', 200, 1),
  ('Pan Pizza', 'pan-pita', 139, 0),
  ('Pan Pizza', 'jamon-de-pavo', 168, 1),
  ('Pan Pizza', 'pure-de-jitomate', 55, 2),
  ('Pan Pizza', 'queso-mozzarella-reducido-en-grasa', 90, 3),
  ('Ricotta Toast', 'pan-integral', 100, 0),
  ('Ricotta Toast', 'fresa-rebanada', 166, 1),
  ('Pollo al Romero', 'pechuga-de-pollo-sin-piel', 180, 0),
  ('Pollo al Romero', 'papa-cocida', 272, 1),
  ('Ensalada Caprese', 'pechuga-de-pollo-sin-piel-a-la-plancha', 150, 0),
  ('Lemon Overnight Oats', 'avena-en-hojuelas', 40, 0),
  ('Lemon Overnight Oats', 'yoghurt-natural', 114, 1),
  ('Lemon Overnight Oats', 'leche', 240, 2),
  ('Lemon Overnight Oats', 'moras', 144, 3),
  ('Hamburguesa Ligera', 'molida-de-res', 150, 0),
  ('Hamburguesa Ligera', 'pan-integral', 50, 1),
  ('Hamburguesa Ligera', 'aguacate-hass', 31, 2),
  ('Hamburguesa Ligera', 'queso-fresco', 30, 3),
  ('Hamburguesa Ligera', 'camote-al-horno', 318, 4),
  ('Carne Asada con Ensalada de Aguacate', 'molida-de-res', 150, 0),
  ('Carne Asada con Ensalada de Aguacate', 'platano-macho', 98, 1),
  ('Carne Asada con Ensalada de Aguacate', 'aguacate-hass', 47, 2),
  ('Carne Asada con Ensalada de Aguacate', 'arroz-cocido', 141, 3),
  ('Bagel de Salmón', 'bagel-integral', 36, 0),
  ('Bagel de Salmón', 'salmon-ahumado', 40, 1),
  ('Chicken Bowl', 'pechuga-de-pollo-sin-piel-a-la-plancha', 150, 0),
  ('Chicken Bowl', 'arroz-cocido', 376, 1),
  ('Chicken Bowl', 'frijol-promedio-cocido', 86, 2),
  ('Chicken Bowl', 'aguacate-hass', 23, 3),
  ('Papa Rellena al Horno', 'molida-de-res', 150, 0),
  ('Papa Rellena al Horno', 'papa-cocida', 204, 1),
  ('Papa Rellena al Horno', 'queso-mozzarella', 30, 2),
  ('Ensalada Cobb', 'pechuga-de-pavo', 150, 0),
  ('Ensalada Cobb', 'huevo-cocido', 44, 1),
  ('Ensalada Cobb', 'aguacate-hass', 23, 2),
  ('Ensalada Cobb', 'queso-panela', 30, 3),
  ('Chicken Honey Mustard Bowl', 'pechuga-de-pollo-sin-piel', 150, 0),
  ('Chicken Honey Mustard Bowl', 'arroz-cocido', 376, 1),
  ('Chicken Honey Mustard Bowl', 'elote-amarillo-desgranado-cocido', 83, 2),
  ('Chicken Honey Mustard Bowl', 'frijol-promedio-cocido', 86, 3),
  ('Desayuno Americano', 'avena-en-hojuelas', 20, 0),
  ('Desayuno Americano', 'huevo-entero-fresco', 88, 1),
  ('Desayuno Americano', 'jamon-de-pavo', 42, 2),
  ('Salmón con Quinoa Bowl', 'salmon', 150, 0),
  ('Salmón con Quinoa Bowl', 'aguacate-hass', 47, 1),
  ('Chicken Tenders Fit', 'pechuga-de-pollo-sin-piel', 120, 0),
  ('Chicken Tenders Fit', 'arroz-cocido', 94, 1),
  ('Wrap', 'tortilla-de-harina-integral', 56, 0),
  ('Wrap', 'huevo-entero-fresco', 44, 1),
  ('Wrap', 'jamon-de-pavo', 42, 2),
  ('Wrap', 'aguacate-hass', 31, 3),
  ('Wrap', 'mandarina', 64, 4),
  ('Chicken Caesar Bowl', 'pechuga-de-pollo-sin-piel-a-la-plancha', 180, 0),
  ('Chicken Caesar Bowl', 'papa-cocida', 272, 1),
  ('Sandwich de Atún', 'atun-en-agua-drenado', 100, 0),
  ('Sandwich de Atún', 'pan-integral', 100, 1),
  ('Sandwich de Atún', 'aguacate-hass', 31, 2),
  ('Sandwich de Atún', 'camote-al-horno', 212, 3),
  ('Shrimp Bowl', 'camaron-cocido', 150, 0),
  ('Shrimp Bowl', 'arroz-cocido', 376, 1),
  ('Shrimp Bowl', 'aguacate-hass', 31, 2),
  ('Sandwich de Guacamole', 'pan-integral', 50, 0),
  ('Sandwich de Guacamole', 'pechuga-de-pollo-sin-piel-cocida', 150, 1),
  ('Sandwich de Guacamole', 'aguacate-hass', 23, 2),
  ('Apple Crumble Avena Horneada', 'avena-en-hojuelas', 40, 0),
  ('Apple Crumble Avena Horneada', 'manzana', 106, 1),
  ('Tacos Tex Mex', 'tortilla-de-maiz', 90, 0),
  ('Tacos Tex Mex', 'molida-de-res', 150, 1),
  ('Tacos Tex Mex', 'queso-parmesano-rallado', 30, 2),
  ('Mac & Cheese Ligero', 'zanahoria-picada-cruda', 64, 0),
  ('Mac & Cheese Ligero', 'queso-manchego', 30, 1),
  ('Mac & Cheese Ligero', 'queso-mozzarella', 30, 2),
  ('Mac & Cheese Ligero', 'pasta-cocida', 240, 3),
  ('Mac & Cheese Ligero', 'pechuga-sin-piel-desmenuzada', 120, 4)
) as x(nombre, food_id, gramos, orden) on x.nombre = i.nombre;
