-- ════════════════════════════════════════════════════════════════
-- RECONSTRUCCIÓN COMPLETA exercise_videos — 44 videos (lista autoritativa de
-- storage.objects que pasó David). Cubre los 8 que faltaban: remo (×4 grips),
-- sentadilla smith, shrugs trap-bar, upright row, zancadas (barra/mancuernas).
-- 3 variantes nuevas en el banco: remo-maquina-sentado-neutro/-prono, shrugs-trap-bar.
-- ════════════════════════════════════════════════════════════════

DELETE FROM exercise_videos;

INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('abduccion-cadera-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/abduccion-cadera-maquina-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('aduccion-cadera-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/aduccion-interna-pierna-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('cable-crunch', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/cable-crunch-core.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('cardio-caminadora', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/cardio-caminadora.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('cardio-eliptica', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/cardio-eliptica.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('aperturas-polea-cruce', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/cristos-pec-fly-espalda-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('curl-femoral-acostado-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/curl-femoral-acostado-maquina-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('curl-pie-polea-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/curl-polea-maquina-bicep.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('curl-predicador-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/curl-predicador-maquina-bicep.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('elevacion-talones-smith', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/elevacion-talones-smith-pantorrilla-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('shrugs-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/encojimientos-trapecio-barra.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('hiperextensiones', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/extension-espalda-baja-maquina-core.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('curl-femoral-sentado-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/extension-femoral-sentado-pierna-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('fondos-triceps-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/fondos-triceps-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('hiper-45', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/hiperextensiones-gluteo-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('hiperextensiones-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/hiperextensiones-maquina-espalda-baja.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('jalon-amplio', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/jalon-frontal-maquina-espalda-abierto.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('jalon-cerrado', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/jalon-frontal-triangulo-maquina-espalda.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('jalon-neutro', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/jalon-neutro-amplio-espalda-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('elevacion-lateral-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/laterales-hombro-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('levantamiento-piernas-sillas-paralelas', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/levantamiento-piernas-core-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('elevacion-talones-maquina-parada', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/pantorrilla-maquina-parada.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('peso-muerto-convencional-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/peso-muerto-convencional-barra-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('peso-muerto-trap-bar-hex', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/peso-muerto-trap-bar-hex-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('prensa-horizontal', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/prensa-horizontal-pierna-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('prensa-45', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/prensa-maquina-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-declinado-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-declinado-barra-pecho.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-horizontal-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-horizontal-barra-pecho.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-cerrado', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-horizontal-maquina-agarre-neutral-pecho-tricep.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-horizontal-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-horizontal-maquina-pecho.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-inclinado-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-inclinado-barra-pecho.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-inclinado-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-inclinado-maquina-pecho.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-smith', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-militar-hombro-smith.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('press-hombros-maquina', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/press-militar-hombros-maquina.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('remo-bajo-polea', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/remo-bajo-polea-espalda.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('remo-maquina-sentado', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/remo-maquina-espalda-sentado.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('remo-maquina-sentado-neutro', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/remo-sentado-agarre-neutro-maquina-espalda.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('remo-maquina-sentado-prono', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/remo-sentado-agarre-prono.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('sentadilla-smith', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/sentadilla-smith-barra-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('shrugs-trap-bar', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/shrugs-encojimientos-trap-bar.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('triceps-push-down-cuerda', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/triceps-push-down-cuerda.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('upright-row-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/upright-row-barra-al-pecho.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('zancada-estatica-barra', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/zancada-estatica-desplantes-barra-pierna.mp4', 0);
INSERT INTO exercise_videos (exercise_id, video_url, display_order) VALUES ('zancada-estatica-mancuernas', 'https://ltveorvqvvlyivjwxjlc.supabase.co/storage/v1/object/public/healthyspaceclub/GYM/zancada-estatica-desplantes-mancuernas-piernas.mp4', 0);
